### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by Tekki** [preaction/Mojolicious-Plugin-PODViewer#2]
How can we get back these nice looking screens from the original PODRenderer?

**Comment by preaction** [comment]
The CSS used by Mojolicious.org was not part of the package. From what I understand, Sebastian considers templates that start with `/mojo` to be part of the mojolicious.org site and not available to projects, so I did not copy them.

We could provide a basic set of CSS in the built-in layout, but we do not yet. We could start from the [CSS I wrote for Yancy](https://github.com/preaction/Yancy/blob/master/eg/doc-site/myapp.pl#L57-L81). Or, if you can get clear permission to release what mojolicious.org has under the Artistic License used by this project, we can add that to the layout as a default.

**Comment by elcamlost** [comment]
I guess, metacpan is under artistic licence. And its layout is well familiar for everyone in Perl5 community. What do you think about an option which will turn on metacpan styles?

**Comment by Tekki** [comment]
@elcamlost if 'you' is me: My point is that we should have a default design that is responsive and doesn't look like [WorldWideWeb](https://worldwideweb.cern.ch/browser/). Doesn't matter if it's the Metacpan style or the one I proposed in #3.
Preaction's idea it that a user should be able to use perldoc.html.ep in his own application, because of that the design elements should be placed in the layout.
